spring:
  config:
    import: classpath:mongodb/mongodb.yml, classpath:wordnik/wordnik.yml
  data:
    redis:
      port: 6379
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092

nats:
  serverPath: nats://localhost:4222

grpc:
  server:
    port: 9090
