version: "3.8"
services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    ports:
      - "8081:8080"
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 1s
      timeout: 1s
      retries: 5
  nats:
    image: nats
    container_name: nats
    ports:
      - "4223:4222"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"
volumes:
  data:


