name: Build and Run Docker Compose

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  setup-build-publish:
    name: Run Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Gradle project
        run: ./gradlew assemble

      - name: Run Docker Compose
        run: docker compose up --build --force-recreate -d app

      - name: Run tests
        run: ./gradlew test

      - name: Shutdown
        if: always()
        run: docker compose down