name: workflow

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Run Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Gradle project
        run: ./gradlew assemble

      - name: Run Docker Compose
        run: docker compose up --build --force-recreate -d

      - name: Run tests
        run: ./gradlew test

      - name: Shutdown
        if: always()
        run: docker compose down
